configs:
  hasher:
    file: ./hasher/hasher.rb
  rng:
    file: ./rng/rng.py
  worker:
    file: ./worker/worker.py
  webui:
    file: ./webui/webui.js
services:
  hasher:
    command:
      - hasher.rb
    configs:
      - 
        mode: 0400
        source: hasher
        target: /hasher.rb
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: ruby
    expose:
      - 8080
    image: amikshas/dockercoins:2021-10-hasher
    networks:
      - hasher
  redis:
    deploy:
      placement:
        constraints:
          - node.role == worker
    expose:
      - 6379
    image: library/redis:alpine
    networks:
      - redis
    volumes:
      - redis:/data/
  rng:
    command:
      - rng.py
    configs:
      - 
        mode: 0400
        source: rng
        target: /rng.py
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: python
    expose:
      - 8080
    image: amikshas/dockercoins:2021-10-rng
    networks:
      - rng
    volumes:
      - 
        target: /usr/local/lib/python3.10/__pycache__/
        type: tmpfs
      - 
        target: /usr/local/lib/python3.10/http/__pycache__/
        type: tmpfs
  webui:
    command:
      - webui.js
    configs:
      - 
        mode: 0400
        source: webui
        target: /webui.js
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: node
    expose:
      - 8080
    image: amikshas/dockercoins:2021-10-webui
    networks:
      - redis
    ports:
      - 8080
  worker:
    command:
      - worker.py
    configs:
      - 
        mode: 0400
        source: worker
        target: /worker.py
    deploy:
      placement:
        constraints:
          - node.role == worker
    entrypoint: python
    image: amikshas/dockercoins:2021-10-worker
    networks:
      - hasher
      - redis
      - rng
    volumes:
      - 
        target: /usr/local/lib/python3.10/distutils/__pycache__/
        type: tmpfs
version: '3.8'
volumes:
  redis:
